services:
  kafka:
    image: 'bitnami/kafka:3.8.0'
    container_name: kafka
    hostname: kafka
    restart: always
    ports:
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://kafka:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  api-gateway:
    image: backend/api-gateway
    build:
      context: ./api-gateway
    container_name: backend-api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - kafka
      - identify-service
      - product-service
      - cart-service
      - order-service

  identify-service:
    image: backend/identify-service
    build:
      context: ./identify-service
    container_name: backend-identify-service
    ports:
      - "8080:8080"
  product-service:
    image: backend/product-service
    build:
      context: ./product-service
    container_name: backend-product-service
    ports:
      - "8081:8081"
  cart-service:
    image: backend/cart-service
    build:
      context: ./cart-service
    container_name: backend-cart-service
    ports:
      - "8082:8082"
  order-service:
    image: backend/order-service
    build:
      context: ./order-service
    container_name: backend-order-service
    ports:
      - "8083:8083"
  payment-service:
    image: backend/payment-service
    build:
      context: ./payment-service
    container_name: backend-payment-service
    ports:
      - "8084:8084"
  review-service:
    image: backend/review-service
    build:
      context: ./review-service
    container_name: backend-review-service
    ports:
      - "8085:8085"
  chat-service:
    image: backend/chat-service
    build:
      context: ./chat-service
    container_name: backend-chat-service
    ports:
      - "8086:8086"
volumes:
  db-data: