version: '3.8'
services:
  api-gateway:
    image: backend/api-gateway
    build:
      context: ./api-gateway
    container_name: backend-api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - identify-service

  identify-service:
    image: backend/identify-service
    build:
      context: ./identify-service
    container_name: backend-identify-service
    ports:
      - "8080:8080"
  product-service:
    image: backend/product-service
    build:
      context: ./product-service
    container_name: backend-product-service
    ports:
      - "8081:8081"
volumes:
  db-data: