server:
  port: 8082
  servlet:
    context-path: /cart
spring:
  application:
    name: cart-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}

app:
  service:
    product: http://product-service:8081